include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/screens/demo/demo_view.dart
    - virgil-e3kit-flutter/**
    - lib/screens/home/chat/components/chat_decrypted_channel_preview.dart
  errors:
    todo: ignore
  plugins:
    - dart_code_metrics

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: true
    always_specify_types: true
    lines_longer_than_80_chars: false
    type_annotate_public_apis: false

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    lines-of-code: 200
    number-of-methods: 10
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 5
    source-lines-of-code: 50
  metrics-exclude:
    - build/**
    - test/**
    - android/**
    - ios/**
    - lib/generated/**
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/screens/demo/demo_view.dart
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - always-remove-listener
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-arguments
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration